import argparse

from ga_replay.replay import simulate_from_itinerary 
from ga_replay.replay import REQUEST_FUNCTIONS

parser = argparse.ArgumentParser(description='Replay Google Analytics traffic')
parser.add_argument('itinerary', type=str,
                    help='The itinerary to run, generated by get_itinerary.py')
parser.add_argument('request_function', type=str,
                    help='The request function to use - in `ga_replay.replay.REQUEST_FUNCTIONS`')
parser.add_argument('--start', type=str, default=None)
args = parser.parse_args()

request_func = REQUEST_FUNCTIONS[args.request_function]

simulate_from_itinerary(args.itinerary, request_func=request_func, 
    start_time=args.start)
